basePath: /api/v1
info:
  contact: {}
  description: API for task management system built with Go and MongoDB.
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  title: Task Management System API
  version: 0.1.0
paths: {}
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
